// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB0Q2b0BcxxoyyiUyVeWzFyTyLSgmzw41w',
    appId: '1:513307927964:web:e351fe17b71c27caf9d459',
    messagingSenderId: '513307927964',
    projectId: 'backend-work-e5be8',
    authDomain: 'backend-work-e5be8.firebaseapp.com',
    databaseURL: 'https://backend-work-e5be8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backend-work-e5be8.appspot.com',
    measurementId: 'G-5CZ5T0SJMS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN1Vrlr9vX_HqTbrbPVd02tCOQ8_-h_1w',
    appId: '1:513307927964:android:db700cf79638d870f9d459',
    messagingSenderId: '513307927964',
    projectId: 'backend-work-e5be8',
    databaseURL: 'https://backend-work-e5be8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backend-work-e5be8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDv2g5xvc5y7IWsrcjoMTMoUMI1DAHvU8w',
    appId: '1:513307927964:ios:f34cf5bac2978968f9d459',
    messagingSenderId: '513307927964',
    projectId: 'backend-work-e5be8',
    databaseURL: 'https://backend-work-e5be8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backend-work-e5be8.appspot.com',
    iosBundleId: 'com.example.backendWork2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDv2g5xvc5y7IWsrcjoMTMoUMI1DAHvU8w',
    appId: '1:513307927964:ios:f34cf5bac2978968f9d459',
    messagingSenderId: '513307927964',
    projectId: 'backend-work-e5be8',
    databaseURL: 'https://backend-work-e5be8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backend-work-e5be8.appspot.com',
    iosBundleId: 'com.example.backendWork2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB0Q2b0BcxxoyyiUyVeWzFyTyLSgmzw41w',
    appId: '1:513307927964:web:24fcba49bd4d46d9f9d459',
    messagingSenderId: '513307927964',
    projectId: 'backend-work-e5be8',
    authDomain: 'backend-work-e5be8.firebaseapp.com',
    databaseURL: 'https://backend-work-e5be8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'backend-work-e5be8.appspot.com',
    measurementId: 'G-J1LL7FSWP7',
  );
}
